### PR TITLE
Fix inaccuracies in polyco specification docstring

### PR DESCRIPTION
**Pull request by theXYZT**
While fixing PINT's polyco implementation, I had also fixed inaccuracies in our polyco specification docstring. Thought it would be nice to make sure the version in baseband-tasks is also fixed.

### CODE REVIEW

**Comment by mhvk** [comment]
This looks good. But my original description came directly from the included reference. Is there another concrete one that shows that the tempo1 description is not valid? Though I guess in practice my code does insist on spaces being present...

**Comment by theXYZT** [comment]
Yeah, I provided that source for posterity. It is, in fact, wrong and does not match the how Polycos are actually generated. 

The modifications match the code that generates Polycos in tempo2 (see the repository) based on what and how it is actually printed to file.

**Comment by theXYZT** [comment]
See: https://bitbucket.org/psrsoft/tempo2/src/345350b99bc9f03f220d8d5fcdec42fa7c72c738/polyco.C#lines-409

**Comment by mhvk** [comment]
Never got around to actually merging this. Now looking at it again, I felt the only change that would be good is to link directly to where the polyco file is generated in tempo2. So, that's done in #222, adding a commit to yours.

**Pull request closed without merging**
