### PR TITLE
Rename to baseband tasks

### PR DESCRIPTION
**Pull request by mhvk**

### CODE REVIEW

**Comment by mhvk** [comment]
@00rebe, @danasimard, @KeithBoehler, @luojing1211, @potato-aardvark - the `scintillometry` project has been renamed to `baseband-tasks` (since what it did had little to do with scintillometry...). Since you are listed as having a fork, probably good to update (though I think things will redirect mostly appropriately).

Documentation will now be at https://baseband.readthedocs.io/projects/baseband-tasks/en/latest/index.html

**Comment by mhvk** [comment]
@pllim - I renamed my project `mhvk/scintillometry` to `mhvk/baseband-tasks` - since I love the auto-updates for problems, could you change it in the list you are keeping?? Thanks!!

**Comment by pllim** [comment]
@mhvk , I don't keep any official list. 😬 Every auto-update from me is done in a "small batch organic" way.

I see that your package doesn't use `astropy-helpers` (for which it does have a list) nor listed in Affiliated. So, I think you are GTG.

**Comment by mhvk** [comment]
@pllim - much appreciated! Indeed, appreciation is official: see at end of https://baseband.readthedocs.io/projects/baseband-tasks/en/latest/authors_for_sphinx.html

**Pull request merged**
